Create 2021-11-13-Docker-Windows.md
BulletTech/BulletTech pull request #76
Opened 2021-11-13 09:28 UTC by Tina0330

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2021-11-13 09:35 UTC, jhqian0909 commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +有些软件在电脑中的成功运行会因为系统的不兼容，需要一些先决条件。不管是参考具体的官方文档还是搜索一些避雷的经验贴，安装成功并使用后，你会发现这些环境的搭建是一劳永逸的，快尝试在你的Windows系统中运行docker吧！之后我们还会持续分享docker的学习经验，敬请期待。
感觉第一句话有点语病。Docker要大写。

2021-11-13 09:36 UTC, jhqian0909 requested changes
Thanks.

2021-11-13 10:49 UTC, Realvincentyuan approved these changes
macOS YYDS

2021-11-13 10:49 UTC, Realvincentyuan commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +在上文[Docker初体验](https://mp.weixin.qq.com/s/gfO5BiK9fqRtWf8rjP8mPA)中我们介绍了Docker的一些基本概念和常用命令，但因为Docker是在Linux系统下创建的资源分离机制，所以它无法在Windows系统下直接运行。这次我们将用3分钟的时间介绍一下如何在Win10系统下运行Docker。
引用的时候记得手动插入链接，不然会变成纯文本

2021-11-13 10:49 UTC, Realvincentyuan commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +这是因为Docker无法在Windows系统中直接运行，而需要创建一个Wins系统中的Linux虚拟机（VM）为Docker的正常运行搭建好底层依赖。虽然[官方文档](https://docs.docker.com/desktop/windows/install/#wsl-2-backend 'WSL2的安装')提供了hyper-V和WSL2两种解决方案，但是WSL2是基于hpyer-v在WSL
Windows系统？不是wins系统吧？

2021-11-13 10:49 UTC, Realvincentyuan commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +首先，需要在通用设置下，勾选使用WSL2基础的引擎，如图所示：
空一行比较安全

2021-11-13 14:02 UTC, Tina0330 commented
@Realvincentyuan @jhqian0909 修改了，伙伴们。谢谢！

2021-11-14 10:41 UTC, jz263 commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +这是因为Docker无法在Windows系统中直接运行，而需要创建一个Windows系统中的Linux虚拟机（VM）为Docker的正常运行搭建好底层依赖。虽然[官方文档](https://docs.docker.com/desktop/windows/install/#wsl-2-backend 'WSL2的安装')提供了hyper-V和WSL2两种解决方案，但是WSL2是基于hpyer-v在
typo: 第二个hyper-V

2021-11-14 10:45 UTC, jz263 approved these changes

2021-11-14 10:51 UTC, Tina0330 commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +这是因为Docker无法在Windows系统中直接运行，而需要创建一个Windows系统中的Linux虚拟机（VM）为Docker的正常运行搭建好底层依赖。虽然[官方文档](https://docs.docker.com/desktop/windows/install/#wsl-2-backend 'WSL2的安装')提供了hyper-V和WSL2两种解决方案，但是WSL2是基于hpyer-v在
改了，谢谢嘉杰！

2021-11-14 11:38 UTC, EchoTang04 approved these changes

2021-11-14 11:38 UTC, EchoTang04 commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +首先，打开`Powershell`命令提示符，运行命令先查看网上所有的子系统， 再选择你想要选择的系统，这里我们将选择Ubuntu来进行安装。
是否要以管理员身份运行才可以？如果是 可以强调一下。

2021-11-14 11:39 UTC, Tina0330 commented on docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
> +首先，打开`Powershell`命令提示符，运行命令先查看网上所有的子系统， 再选择你想要选择的系统，这里我们将选择Ubuntu来进行安装。
我直接打开就运行了，你安装的时候有提示吗，糖糖

2021-11-14 12:03 UTC, jhqian0909 approved these changes

2021-11-14 12:14 UTC, merged